CREATE TABLE IF NOT EXISTS tpsl_backtest_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    run_id VARCHAR(64) NOT NULL COMMENT '回测运行编号',
    start_date DATE NOT NULL COMMENT '回测开始日期',
    end_date DATE NOT NULL COMMENT '回测结束日期',
    retrain_frequency VARCHAR(24) NOT NULL COMMENT '模型重训频率',
    execution_mode VARCHAR(24) NOT NULL COMMENT '成交模拟模式',
    stop_order_type VARCHAR(24) NOT NULL COMMENT '止损订单类型',
    symbol_count INT NOT NULL COMMENT '回测股票数量',
    fold_count INT NOT NULL DEFAULT 0 COMMENT '滚动训练批次数量',
    status VARCHAR(24) NOT NULL COMMENT '回测状态',
    config_json JSON NULL COMMENT '回测配置',
    metrics_json JSON NULL COMMENT '回测汇总指标',
    error_message VARCHAR(2000) NULL COMMENT '失败错误信息',
    started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '开始时间',
    finished_at DATETIME NULL COMMENT '结束时间',
    PRIMARY KEY (id),
    KEY idx_backtest_runs_run_id (run_id),
    KEY idx_backtest_runs_dates (start_date, end_date),
    KEY idx_backtest_runs_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
COMMENT='滚动回测运行记录表';

CREATE TABLE IF NOT EXISTS tpsl_backtest_trades (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
    run_id VARCHAR(64) NOT NULL COMMENT '回测运行编号',
    strategy VARCHAR(32) NOT NULL COMMENT '策略名称',
    fold_train_end_date DATE NOT NULL COMMENT '该批模型训练截止日期',
    signal_date DATE NOT NULL COMMENT '生成条件单的交易日期',
    execution_date DATE NOT NULL COMMENT '模拟成交日期',
    symbol VARCHAR(24) NOT NULL COMMENT '股票统一代码',
    close_price DECIMAL(20, 6) NOT NULL COMMENT '信号日收盘价',
    take_profit_price DECIMAL(20, 6) NOT NULL COMMENT '止盈价格',
    stop_trigger_price DECIMAL(20, 6) NOT NULL COMMENT '止损触发价格',
    stop_limit_price DECIMAL(20, 6) NOT NULL COMMENT '止损限价',
    next_open DECIMAL(20, 6) NOT NULL COMMENT '次日开盘价',
    next_high DECIMAL(20, 6) NOT NULL COMMENT '次日最高价',
    next_low DECIMAL(20, 6) NOT NULL COMMENT '次日最低价',
    next_close DECIMAL(20, 6) NOT NULL COMMENT '次日收盘价',
    exit_price DECIMAL(20, 6) NOT NULL COMMENT '模拟退出或估值价格',
    outcome VARCHAR(40) NOT NULL COMMENT '模拟结果类型',
    return_pct DECIMAL(14, 8) NOT NULL COMMENT '单次收益率',
    confidence DECIMAL(10, 6) NULL COMMENT '模型内部置信度',
    risk_reward_ratio DECIMAL(14, 6) NULL COMMENT '建议盈亏比',
    stop_limit_unfilled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '止损限价是否未成交',
    dual_hit TINYINT(1) NOT NULL DEFAULT 0 COMMENT '次日是否同时触及止盈止损',
    gap_stop TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否跳空触发止损',
    model_version VARCHAR(64) NULL COMMENT '模型版本',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (id),
    KEY idx_backtest_trades_run_strategy (run_id, strategy),
    KEY idx_backtest_trades_signal_date (signal_date),
    KEY idx_backtest_trades_symbol_date (symbol, signal_date),
    KEY idx_backtest_trades_outcome (outcome)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
COMMENT='滚动回测交易明细表';
